<?php
define("PERM_MAPPING_VIEW_OBJECTS", 'View Mapping Interface');

function mapping_menu() {
  $items['mapping'] = array(
    'title' => t('Mapping'),
    'description' => t('Mapping.'),
    'page callback' => 'mapping',
    'access arguments' => array(PERM_MAPPING_VIEW_OBJECTS),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function mapping_permission() {
  return array(
    PERM_MAPPING_VIEW_OBJECTS  => array(
      'title' => t(PERM_MAPPING_VIEW_OBJECTS),
      'description' => t('View BAMP Mapping Interface.'),
      'restrict access' => TRUE,
    ),
  );
}

function mapping_theme() {
  return array(
    'mapping' => array(
      'arguments' => array('pid' => NULL),
      'template' => 'Viewer',
    ),
  );
}

function template_preprocess_mapping(array &$variables) {
  global $base_url;
}

function mapping($pid = NULL) {
    //Get the path to this module
    $path = drupal_get_path('module', 'mapping');

    //Path of javascript files
    $js_path = $path . '/js';

    //Path of ExtJS Library
    $ext_path = $path . '/lib/ext';

    //Add Javascript and CSS files
    drupal_add_js('http://maps.google.com/maps/api/js?sensor=false');//Google Maps API
    drupal_add_js($ext_path . '/ext-all-debug-w-comments.js');//ExtJS Library
    drupal_add_css($path . '/css/Clear.css');//Clears browser styles
    drupal_add_css($ext_path . '/resources/css/ext-all-gray.css', 'theme', 'all');//EXT Theme CSS
    drupal_add_js($js_path . '/init.js');//Defines stores and module paths
    drupal_add_js($js_path . '/lib/GMapPanel3.js');//EXT GMapPanel class
    drupal_add_js($js_path . '/lib/polygonCreator/v1/polygon.js');//Polygon creator class
    drupal_add_js($js_path . '/panels/mapPanel.js');//Map and Legend Panel
    drupal_add_js($js_path . '/panels/filterPanelElements.js');//Form elements for filters
    drupal_add_js($js_path . '/panels/filterPanel.js');//Right Hand filter panel
    drupal_add_js($js_path . '/mapping.js');
    drupal_add_css($path . '/css/mapping.css');
    return theme('mapping', $pid);
}
