<?php
// $Id$
include 'csvupload.common.inc';
include 'csvupload.upload.inc';


/**
* Your module will use the subject as the main title and load the content from your function
*/
function csvupload_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('CSVUpload');
      return $blocks;
      break;

    case 'view':
      $blocks['subject'] = t('CSVUpload');
      $blocks['content'] = csvupload_block_content();
      return $blocks;
  }
}

/**
* Your module should generate it's content here. This will be displayed within your module
*/
function csvupload_block_content() {
  $content .= "Replace with your logic";
  return $content;
}

/**
* This will allow you to restrict certain actions of the module to certain roles
*/
function csvupload_perm() {
  return array('access csvupload', 'administer csvupload');
}

/**
* This will provide users with more information about your module
*/
function csvupload_hook_help($path, $arg) {
  switch ($path) {
    case 'admin/help#csvupload':
      $output = t('Help Content Goes Here');
      return $output;
      break;
  }
}

/**
* CSV Upload Menua
*/
function csvupload_menu() {
  $items = array();
  $items['csvupload'] = array(
    'title' => 'CSV Upload',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('csvupload_upload_form'),
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
    'weight' => '1',
  );
  return $items;
}
