<?php
// $Id$

include 'csvupload.common.inc';
include 'csvupload.upload.inc';

/**
* Your module will use the subject as the main title and load the content from your function
*/
function csvupload_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('CSVUpload');
      return $blocks;
      break;

    case 'view':
      $blocks['subject'] = t('CSVUpload');
      $blocks['content'] = csvupload_block_content();
      return $blocks;
  }
}

/**
* Your module should generate it's content here. This will be displayed within your module
*/
function csvupload_block_content() {
  $content .= "Replace with your logic";
  return $content;
}

/**
* This will allow you to restrict certain actions of the module to certain roles
*/
function csvupload_perm() {
  return array('access csvupload', 'administer csvupload');
}

/**
* This will provide users with more information about your module
*/
function csvupload_hook_help($path, $arg) {
  switch ($path) {
    case 'admin/help#csvupload':
      $output = t('Help Content Goes Here');
      return $output;
      break;
  }
}

/**
* This will create an admin menu
*/
function csvupload_menu() {
  $items = array();
  $items['csvupload'] = array(
    'title' => 'CSV Upload',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('csvupload_upload_form'),
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
    'weight' => '1',
  );

  $items['admin/settings/csvupload'] = array(
    'title' => 'csvupload',
    'description' => 'CSVupload module allows you to specify database tables you would like to enable for importing files.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('csvupload_settings'),
    'access arguments' => array('administer csvupload'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
* This will construct the form used within the admin menu
*/
function csvupload_settings() {
  $dbh = Database::getConnection('bamp_new','default');

  $form['csvupload_general_settings'] = array(
    '#title' => t('General CSV Upload Settings'),
    '#type' => "fieldset",
    '#collapsible' => TRUE,
  );
  $form['csvupload_general_settings']['text'] = array(
    '#title' => t('Select Importable Tables'),
    '#type' => "fieldset",
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $tables = $dbh->query("show tables")->fetchCol();

  foreach ($tables as $k => $table) {
    $form['csvupload_general_settings']['text'][$table] = array(
      '#title' => $table,
      '#type' => "checkbox",
      '#default_value' => variable_get($table, FALSE) //false by default
    );
  }
  return system_settings_form($form);
}
