<?php
// $Id$

/**
 * @file
 * Contains code for displaying list of reports
 */

/**
 * Set up permissions for module 
 * http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_permission/7
 */
function ireport_permission() {
  return array(
    'View data'  => array(
      'title' => t('View data'),
      'description' => t('Allow user to view BAMP data.'),
      'restrict access' => TRUE,
    ),
  );
}//end ireport_perm


/**
 * Drupal Menu Hook
 * http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_menu/7
 */
function ireport_menu()
{
  $items = array ();
  $items['ireport/view'] = array(
    'title' => 'BAMP Reports',
    'page callback' => 'ireport_report_list',
    'access callback' => 'user_access',
    'access arguments' => array('View data'),
    'weight' => '1',
  );
  $items['ireport/bampsearch'] = array(
    'title' => 'BAMP Search',
    'page callback' => 'ireport_search_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('View data'),
    'weight' => '1',
  );
  $items['ireport/bampsearch/wildsamplinginstances'] = array(
    'title' => 'Wild Sampling Instances Table',
    'page callback' => 'ireport_wild_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('View data'),
  );
  $items['ireport/bampsearch/wildfishsamples'] = array(
    'title' => 'Wild Fish Samples Table',
    'page callback' => 'ireport_wild_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('View data'),
  );
  $items['ireport/bampsearch/wildlicedetails'] = array(
    'title' => 'Wild Lice Details Table',
    'page callback' => 'ireport_wild_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('View data'),
  );
  $items['ireport/bampsearch/farmaggregate'] = array(
    'title' => 'Farm Aggregate Table',
    'page callback' => 'ireport_farm_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('View data'),
  );
  $items['ireport/bampsearch/farmenvironment'] = array(
    'title' => 'Farm Environment Table',
    'page callback' => 'ireport_farm_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('View data'),
  );
  $items['ireport/bampsearch/farminventory'] = array(
    'title' => 'Farm Inventory Table',
    'page callback' => 'ireport_farm_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('View data'),
  );
  $items['ireport/bampsearch/farmfishdata'] = array(
    'title' => 'Farm Fish Data Table',
    'page callback' => 'ireport_farm_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('View data'),
  );
  $items['ireport/bampsearch/farmsites'] = array(
    'title' => 'Farm Sites Table',
    'page callback' => 'ireport_farm_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('View data'),
  );

  return $items;
}

function ireport_search_menu_callback() {
  drupal_set_title('Search Menu');
  
  $content['form'] = array(
    '#markup' => '<p> This is the BAMP main menu</p>',
  );  

  return $content;
}

function ireport_wild_search_page() {
  drupal_set_title('Wild Data Search');
  $content ['form'] = array(
    '#markup' => '<p></p>',
  );
  return $content;
}

function ireport_farm_search_page() {
  drupal_set_title('Farm Data Search');
  $content ['form'] = array(
    '#markup' => '<p></p>',
  );
  return $content;
}


/**
 * Contains returns views api version for views integration 
 * http://drupal.org/project/views
 */
function ireport_views_api() {
  return array('api' => 3.0);
}

function ireport_report_list() {
  $sql = "SELECT vv.human_name, vv.description, vd.display_options  ";
  $sql.= "FROM views_view vv ";
  $sql.= "INNER JOIN views_display vd ON vv.vid = vd.vid ";
  $sql.= "WHERE vd.display_plugin = 'page' ";
  $sql.= "AND vv.tag = 'BAMP'";

  $limit = 20;
  $header = array(
    array('data' => t('Title'), 'field' => 'display_title'),
    array('data' => t('Description'), 'field' => 'company'),
    array('data' => t('View Report'), 'field' => 'city')
  );
  $result = db_query($sql);
  $rows = array();
  while($row = $result->fetchAssoc()) {
    $display_options = unserialize($row['display_options']);
    $title = $row['human_name'];
    $description = $row['description'];
    $link = l('View Report', $display_options['path']);

    $rows[] = array($title, $description, $link);
  }
  if (!$rows) {
    $rows[] = array(array('data' => t('No reports have been created yet.'), 'colspan' => 3));
  }

  $output = theme('table', array(
    'header' => $header, 
    'rows' => $rows,
  ));

  return $output;
}
