<?php
// $Id$

/**
 * @file
 * Contains code for displaying list of reports
 */

/**
 * Set up permissions for module 
 * http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_permission/7
 */
function ireport_perm() {
  return array('access ireport','administer ireport');
}//end ireport_perm


/**
 * Drupal Menu Hook
 * http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_menu/7
 */
function ireport_menu()
{
  $items = array ();
  $items['ireport/view'] = array(
    'title' => 'BAMP Reports',
    'page callback' => 'ireport_report_list',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
    'weight' => '1',
  );
  $items['ireport/bampsearch'] = array(
    'title' => 'BAMP Search',
    'page callback' => 'ireport_search_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
    'weight' => '1',
  );
  $items['ireport/bampsearch/wildsites'] = array(
    'title' => 'Wild Sites Search',
    'page callback' => 'ireport_wild_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
  );
  $items['ireport/bampsearch/wildtrips'] = array(
    'title' => 'Wild Trips Search',
    'page callback' => 'ireport_wild_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
  );
  $items['ireport/bampsearch/wildlab'] = array(
    'title' => 'Wild Lab Results Search',
    'page callback' => 'ireport_wild_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
  );
  $items['ireport/bampsearch/wildfish'] = array(
    'title' => 'Wild Fish Level Search',
    'page callback' => 'ireport_wild_search_page',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
  );

  return $items;
}

function ireport_search_menu_callback() {
  drupal_set_title('Search Menu');
  
  $content['form'] = array(
    '#markup' => '<p> This is the BAMP main menu</p>',
  );  

  return $content;
}

function ireport_wild_search_page() {
  drupal_set_title('Wild Data Search');
  $content ['form'] = array(
    '#markup' => '<p>Please use the search block below to search BAMP Wild Information</p>',
  );
  return $content;
}

/**
 * Contains returns views api version for views integration 
 * http://drupal.org/project/views
 */
function ireport_views_api() {
  return array('api' => 3.0);
}

function ireport_report_list() {
  $sql = "SELECT vv.human_name, vv.description, vd.display_options  ";
  $sql.= "FROM views_view vv ";
  $sql.= "INNER JOIN views_display vd ON vv.vid = vd.vid ";
  $sql.= "WHERE vd.display_plugin = 'page' ";
  $sql.= "AND vv.tag = 'BAMP'";

  $limit = 20;
  $header = array(
    array('data' => t('Title'), 'field' => 'display_title'),
    array('data' => t('Description'), 'field' => 'company'),
    array('data' => t('View Report'), 'field' => 'city')
  );
  $result = db_query($sql);
  $rows = array();
  while($row = $result->fetchAssoc()) {
    $display_options = unserialize($row['display_options']);
    $title = $row['human_name'];
    $description = $row['description'];
    $link = l('View Report', $display_options['path']);

    $rows[] = array($title, $description, $link);
  }
  if (!$rows) {
    $rows[] = array(array('data' => t('No reports have been created yet.'), 'colspan' => 3));
  }

  $output = theme('table', array(
    'header' => $header, 
    'rows' => $rows,
  ));

  return $output;
}
